<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>moin</string>
	</array>
	<key>name</key>
	<string>ADP Moin</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Headers</string>
			<key>match</key>
			<string>^=.+=</string>
			<key>name</key>
			<string>invalid.heading.moin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.bold.moin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Bold</string>
			<key>match</key>
			<string>\'{3}(.+)\'{3}</string>
			<key>name</key>
			<string>keyword1.boldall.moin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.italic.moin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>italic</string>
			<key>match</key>
			<string>\'{2}(.+)\'{2}[^']?</string>
			<key>name</key>
			<string>keyword1.italic.moin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.underline.moin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>underscore</string>
			<key>match</key>
			<string>\_{2}(.+)\_{2}</string>
			<key>name</key>
			<string>keyword1.underline.moin</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Unordered Lists</string>
			<key>match</key>
			<string>\s\*\s</string>
			<key>name</key>
			<string>comment.unordered.moin</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ordered Lists</string>
			<key>match</key>
			<string>\s[1aAiI]\.\s</string>
			<key>name</key>
			<string>keyword.ordered.moin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.link.moin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Links</string>
			<key>match</key>
			<string>\[\[([^\|\]]+)</string>
			<key>name</key>
			<string>support.function.link.moin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.link.moin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Links</string>
			<key>match</key>
			<string>\{\{([^}]+)\}\}</string>
			<key>name</key>
			<string>support.function.image.moin</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.linkname.moin</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Links</string>
			<key>match</key>
			<string>\|([^\|\]]+)</string>
			<key>name</key>
			<string>keyword.moin</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Links</string>
			<key>match</key>
			<string>(\{{2}|\}{2}|\[{2}|\]{2}|\||\{{3}|\}{3})</string>
			<key>name</key>
			<string>support.function.moin</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.moin</string>
	<key>uuid</key>
	<string>78ed4c60-cb2f-4cd7-8d13-1632eab179aa</string>
</dict>
</plist>
